linters-settings:
  misspell:
    locale: US
  govet:
    enable:
      - nilness
  staticcheck:
    checks:
      - "all" # Include all checks except the ones below.
      - "-SA1019" # Do not block the build if deprecated functions or packages are used.

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
