linters-settings:
  misspell:
    locale: US
  govet:
    enable:
      - nilness

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
