version: "2"
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    govet:
      enable:
        - nilness
    misspell:
      locale: US
    staticcheck:
      checks:
        # These are processed in order. It is important that the inclusion
        # comes before the exclusion.
        - all
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
