before:
  hooks:
    - go mod download
builds:
- main: ./main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin 
  ignore:
  - goarch: 386
  ldflags:
  - -s -w -X github.com/instrumenta/conftest/internal/commands.version={{.Version}} -X github.com/instrumenta/conftest/internal/commands.commit={{.ShortCommit}} -X github.com/instrumenta/conftest/internal/commands.date={{.Date}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
      - LICENSE
      - README.md
      - plugin/*.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- github:
    owner: instrumenta
    name: homebrew-instrumenta
  folder: Formula
  description: "Test your configuration using Open Policy Agent"
  homepage: "https://github.com/instrumenta/conftest"
  test: |
    system "#{bin}/conftest --version"
scoop:
  bucket:
    owner: instrumenta
    name: scoop-instrumenta
  description: "Test your configuration using Open Policy Agent"
  homepage: "https://github.com/instrumenta/conftest"
nfpms:
  - bindir: /usr/bin
    description: "Test your configuration using Open Policy Agent"
    formats:
      - deb
      - rpm
    homepage: https://github.com/instrumenta/conftest
    license: Apache-2.0
snapcrafts:
  - summary: "Test your configuration using Open Policy Agent"
    publish: false
    description: |
      Conftest helps you write tests against structured configuration data. Using Conftest you can write tests for your Kubernetes configuration, Tekton pipeline definitions, Terraform code, Serverless configs or any other config files.

      Conftest uses the Rego language from Open Policy Agent for writing the assertions. You can read more about Rego in How do I write policies in the Open Policy Agent documentation
    grade: stable
    confinement: strict
    license: Apache-2.0
    apps:
      conftest:
        plugs: ["home", "network"]
