before:
  hooks:
  - go mod download

builds:
- main: ./main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - "-s"
  - "-w"
  - "-X github.com/open-policy-agent/conftest/internal/commands.version={{.Version}}"

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
      - LICENSE
      - README.md
      - plugin/*.sh

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# Publishes the deb and rpm files to the GitHub releases page.
nfpms:
  - bindir: /usr/bin
    description: "Test your configuration using Open Policy Agent"
    formats:
      - deb
      - rpm
    homepage: https://github.com/open-policy-agent/conftest
    maintainer: jpreese <john@reese.dev>
    license: Apache-2.0
